From 6ffa54ed7ca56047b26f05cc6b9967820fa5dc21 Mon Sep 17 00:00:00 2001
From: Radek Vykydal <rvykydal@redhat.com>
Date: Wed, 19 Aug 2020 13:51:14 +0200
Subject: [PATCH] network: do not try to activate connection that has not been
 found

Resolves: rhbz#1869323
---
 pyanaconda/modules/network/nm_client.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/pyanaconda/modules/network/nm_client.py b/pyanaconda/modules/network/nm_client.py
index 2f5703e76..acf6f7858 100644
--- a/pyanaconda/modules/network/nm_client.py
+++ b/pyanaconda/modules/network/nm_client.py
@@ -785,8 +785,9 @@ def ensure_active_connection_for_device(nm_client, uuid, device_name, only_repla
             active_uuid = ac.get_uuid() if ac else None
             if uuid != active_uuid:
                 ifcfg_con = nm_client.get_connection_by_uuid(uuid)
-                activate_connection_sync(nm_client, ifcfg_con, None)
-                activated = True
+                if ifcfg_con:
+                    activate_connection_sync(nm_client, ifcfg_con, None)
+                    activated = True
     msg = "activated" if activated else "not activated"
     log.debug("ensure active ifcfg connection for %s (%s -> %s): %s",
               device_name, active_uuid, uuid, msg)
-- 
2.23.0

